// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicrapBzm0Mf9Ug-RiAABeSvG9BfMmlSI',
    appId: '1:691885124484:web:d23a162c128f44ef460bd1',
    messagingSenderId: '691885124484',
    projectId: 'pollingsystem-fbc37',
    authDomain: 'pollingsystem-fbc37.firebaseapp.com',
    storageBucket: 'pollingsystem-fbc37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNRaAPjWTxSFpdABJE-t0jBugOf_kjAHM',
    appId: '1:691885124484:android:cd277b74bcd54057460bd1',
    messagingSenderId: '691885124484',
    projectId: 'pollingsystem-fbc37',
    storageBucket: 'pollingsystem-fbc37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZsfwZKVR5ngqqVxjyRBj6ml-blxlqtZc',
    appId: '1:691885124484:ios:726cc91bbf6c36f3460bd1',
    messagingSenderId: '691885124484',
    projectId: 'pollingsystem-fbc37',
    storageBucket: 'pollingsystem-fbc37.firebasestorage.app',
    iosBundleId: 'com.example.pollingsys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZsfwZKVR5ngqqVxjyRBj6ml-blxlqtZc',
    appId: '1:691885124484:ios:726cc91bbf6c36f3460bd1',
    messagingSenderId: '691885124484',
    projectId: 'pollingsystem-fbc37',
    storageBucket: 'pollingsystem-fbc37.firebasestorage.app',
    iosBundleId: 'com.example.pollingsys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDicrapBzm0Mf9Ug-RiAABeSvG9BfMmlSI',
    appId: '1:691885124484:web:55aa3b90d8dbef73460bd1',
    messagingSenderId: '691885124484',
    projectId: 'pollingsystem-fbc37',
    authDomain: 'pollingsystem-fbc37.firebaseapp.com',
    storageBucket: 'pollingsystem-fbc37.firebasestorage.app',
  );
}
